version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
       - echo Build started on `date`
      - zip hello.zip ./index.html
  post_build:
    commands:
      - echo "Post build phase"
      - ls -al

artifacts:
  files:
    - '**/*'
