version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  build:
    commands:
      - echo "Build phase"
      - composer install --no-dev
  post_build:
    commands:
      - echo "Post build phase"
      - ls -al

artifacts:
  files:
    - '**/*'
